News/routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\NewsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [NewsController::class, 'index']);

Route::resource('news', NewsController::class);
Route::resource('news.comments', CommentController::class)
    ->only(['store', 'update', 'destroy']);

Auth::routes();

News/app/Models/News.php
<?php

namespace App\Models;

use App\Filters\QueryFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;


class News extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = ['content', 'date_publication', 'user_id', 'category_id'];


    /**
     * @return BelongsTo
     */
    public function user():BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return BelongsTo
     */
    public function category():BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @param Builder $builder
     * @param QueryFilter $filter
     * @return Builder
     */
    public function scopeFilter(Builder $builder, QueryFilter $filter)
    {
        return $filter->apply($builder);
    }
}

News/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\NewsFilter;
use App\Http\Requests\NewsRequest;
use App\Models\Category;
use App\Models\News;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class NewsController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index(NewsFilter  $filter)
    {
        $now =  now();
        $news = News::filter($filter)->where('date_publication', '<=', $now)->paginate(6);
        $categories = Category::all();
        if (Auth::check()) {
            if(Auth::user()->is_admin) {
                $news = News::filter($filter)->orderBy('id', 'desc')->paginate(6);
                return view('news.index', compact('news', 'categories'));
            }
        }

        return view('news.index', compact('news','categories'));
    }


    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::all();
        return view('news.create', compact('categories'));
    }


    /**
     * @param NewsRequest $request
     * @return RedirectResponse
     */
    public function store(NewsRequest $request):RedirectResponse
    {
        $news = new News();
        $news->content = $request->input('content');
        $news->user()->associate($request->user());
        $news->date_publication = $request->input('date_publication');
        $news->category_id = $request->category_id;

        $news->save();
        return redirect()->route('news.index')->with('status', "News successfully created!");
    }


    /**
     * @param News $news
     * @return Application|Factory|View
     */
    public function show(News $news)
    {
        $comments = $news->comments()->orderByDesc('updated_at')->paginate(5);
        return view('news.show', compact('news', 'comments'));
    }


    /**
     * @param News $news
     * @return Application|Factory|View
     */
    public function edit(News $news)
    {
        $categories = Category::all();
        return view('news.edit', compact('news', 'categories'));
    }


    /**
     * @param NewsRequest $request
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(NewsRequest $request, News $news): RedirectResponse
    {
        $this->authorize('update', $news);
        $data = $request->all();
        $news->update($data);

        return redirect()->route('news.index')->with('status', 'News successfully updated!');
    }


    /**
     * @param News $news
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(News $news):RedirectResponse
    {
        $this->authorize('delete', $news);
        $news->delete();
        return redirect()->route('news.index')->with('status', 'Successfully deleted!');
    }
}

News/resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')
    <div>
        <h1>Create news</h1>
        <form enctype="multipart/form-data" method="post" action="{{ route('news.store') }}">
            @csrf
            <div class="form-group">
                <label for="contentNews"><b>News content</b></label>
                <textarea class="form-control" name="content" id="contentNews" cols="30" rows="10" ></textarea>
                @error('content')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            @if(Auth::user()->is_admin )
            <label for="date_publication">Enter a date and time for your party booking:</label>
            <input id="date_publication" type="datetime-local" name="date_publication" value="2022-02-02">
            @endif
            @error('date_publication')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
            <div class="form-group">
                <label for="category"><b>Select a category:</b></label>
                <select class="form-control border-success  @error('category_id') is-invalid border-danger @enderror"
                        id="category"  name="category_id">
                    <option value="" selected >'Choose'</option>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            @error('category_id')
            <p class="text-danger">{{ $message }}</p>
            @enderror

            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
@endsection

News/resources/views/news/edit.blade.php
@extends('layouts.app')
@section('content')
    <div>
        <h1>Edit news</h1>
        <form enctype="multipart/form-data" method="post" action="{{ route('news.update', ['news' => $news]) }}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="contentNews"><b class="text-shadow-white">News content</b></label>
                <textarea class="form-control" name="content" id="contentNews" cols="30" rows="10" >{{$news->content}}</textarea>
                @error('content')
                <div class="alert alert-danger">{{$message}}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="category"><b class="text-shadow-white">Select a category:</b></label>
                <select class="form-control border-success  @error('category_id') is-invalid border-danger @enderror"
                        id="category"  name="category_id">
                    <option value="" selected >'Choose'</option>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}" @if($category == $news->category) selected @endif>{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            @error('category_id')
            <p class="text-danger">{{ $message }}</p>
            @enderror
            <label for="date_publication" class="text-shadow-white">Enter a date and time for your party booking:</label>
            <input id="date_publication" type="datetime-local" name="date_publication" value="{{$news->date_publication}}">
            @error('date_publication')
            <div class="alert alert-danger">{{$message}}</div>
            @enderror
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

News/resources/views/news/index.blade.php
@extends('layouts.app')
@section('content')

    <h1>All news</h1>
    @if(\Illuminate\Support\Facades\Auth::check())
        <div>
            <a href="{{route('news.create')}}" type="button" class="btn btn-sm btn-secondary" >Add news</a>
        </div>
    @endif

    <div class="">
        <form id="form_id" action="{{ route('news.index') }}" method="GET">
            <select name="category_id" class="form-select" aria-label="Default select example" onchange="this.form.submit()">
                <option selected disabled>Choose category</option>
                @foreach($categories as $category)
                    <option @if(isset($_GET['category_id'])) @if($_GET['category_id'] == $category->id)
                            selected @endif @endif value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </form>
    </div>

    <div class="row">
        @if($news->count() > 0)
            @foreach($news as $one_news)
                    <div class="col-4">
                        <div class="card" style="margin: 10px">
                            <div class="card-body">
                                <p class="card-category"><span class="font-weight-bold">Category:</span> {{ $one_news->category->name }}</p>
                                <p class="card-text">{{$one_news->content}}</p>
                                <p class="card-author">Author: {{$one_news->user->name}}</p>
                                @if(!Empty($one_news->category_id))

                                @endif
                                <p class="card-text"><span class="font-weight-bold">Date of creation:</span> {{ $one_news->created_at->format('d M Y ') }}</p>
                                <p class="card-text"><span class="font-weight-bold">Date of publication:</span> {{ date($one_news->date_publication) }}</p>
                                <a href="{{route('news.show', ['news' => $one_news])}}" class="card-link">Show more...</a>
                            </div>
                        </div>
                    </div>
            @endforeach
            <div class="row justify-content-md-center p-5">
                <div class="col-md-auto">
                    {{$news->links('pagination::bootstrap-4') }}
                </div>
            </div>
        @else
            <p>No published news</p>
        @endif
    </div>

@endsection

News/resources/views/news/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-8">
                <div class="card-body">
                    <p class="card-text">{{$news->content}}</p>
                    <h5 class="card-title" style="margin: 5px">Author: {{$news->user->name}}</h5>
                    <p class="card-text"><small class="text-muted">Date of creation {{ $news->created_at->format('d M Y') }}</small></p>
                    <p class="card-text"><small class="text-muted">Date of publication {{ date($news->date_publication) }}</small></p>
                    <div class="btn-group d-flex align-items-center">
                        @can('update', $news)
                        <a href="{{route('news.edit', ['news' => $news])}}" class=" btn-outline-info btn-sm">Edit</a>
                        @endcan
                        @can('delete', $news)
                        <form action="{{route('news.destroy',['news' => $news])}}" method="post">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-outline-danger btn-sm" type="submit">Remove</button>
                        </form>
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if($comments->count() > 0)
        <div class="list-group">
            @foreach($comments as $comment)
                <div class="list-group-item list-group-item-action shadow-lg">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="w-75">
                            <h5 class="mb-1">
                                <a href="" class="text-decoration-none">{{ $comment->user->name }}</a>
                            </h5>
                            <p class="mb-1"><em>{{ $comment->body }}</em></p>

                            <div class="accordion accordion-flush" id="accordionFlushExample">
                                <div class="accordion-item">
                                    <div id="flush-collapse{{ $comment->id }}" class="accordion-collapse collapse"
                                         aria-labelledby="flush-heading"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <form
                                                action="{{ route('news.comments.update', ['news' => $news, 'comment' => $comment]) }}"
                                                method="POST">
                                                @csrf
                                                @method('PUT')
                                                <div class="row">
                                                    <div class="input-group">
                                                    <textarea class="form-control border-info"
                                                              name="body"
                                                              aria-label="With textarea"
                                                              cols="30" rows="5">{{ $comment->body }}</textarea>
                                                    </div>
                                                </div>
                                                <div class="row mt-2 mb-5">
                                                    <div class="col-12">
                                                        <button type="submit" class="btn btn-outline-info">Edit</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <small class="text-muted">{{ $comment->updated_at->diffForHumans() }}</small>
                            @can('delete', $comment)
                                <form
                                    action="{{ route('news.comments.destroy', ['news' => $news, 'comment' => $comment]) }}"
                                    method="POST" class="text-end">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-outline-info btn-sm" type="button" data-toggle="collapse"
                                            data-target="#flush-collapse{{ $comment->id }}" aria-expanded="false"
                                            aria-controls="flush-collapse{{ $comment->id }}">
                                        Edit
                                    </button>
                                    <button type="submit" class="btn btn-outline-danger btn-sm">
                                        Remove
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="row justify-content-md-center mt-5">
            <div class="col-md-auto">
                {{ $comments->withQueryString()->links('pagination::bootstrap-4') }}
            </div>
        </div>
    @endif
    @if(\Illuminate\Support\Facades\Auth::check())
    @if(Auth::user() != $news->user)
        <div>
            <h3 class="mt-5 mb-3 bg-white-heading">Add comment</h3>
            <form action="{{ route('news.comments.store', $news) }}" method="POST">
                @csrf
                <div class="row">
                    <div class="input-group">
                        <textarea class="form-control border-info @error('body') is-invalid border-danger @enderror"
                                  name="body" aria-label="With textarea"
                                  cols="30" rows="5" ></textarea>
                    </div>
                    @error('body')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="row mt-2 mb-5">
                    <div class="col-12">
                        <button type="submit" class="btn-bg-white">Add</button>
                    </div>
                </div>
            </form>
        </div>
    @endif
    @endif
    <a href="{{route('news.index')}}" class="btn-bg-white">Back to all news</a>

@endsection